#pragma once

enum SpritesEnum {
    SPRITE_WALK = 0x00,
    SPRITE_AXE_WALK = 0x01,
    SPRITE_AXE = 0x02,
    SPRITE_JUMPING = 0x03,
    SPRITE_WACCUSE_GETTING_DAMAGE = 0x04,
    SPRITE_WACCUSE_DIE = 0x05,
    SPRITE_WACCUSE_GRAVE = 0x06
};